# jwt-user-cluster-admin.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jwt-user-cluster-admin
subjects:
- kind: User
  name: test   # 👈 this matches the mapped username from your token
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin  # or "view" / "edit"
  apiGroup: rbac.authorization.k8s.io
