kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
         "authentication-config": "/files/AuthenticationConfiguration.yaml"
         "authentication-token-webhook-cache-ttl": "5s"
      extraVolumes:
      - name: api-server-basic-auth-files
        hostPath: "/files"
        mountPath: "/files"
        readOnly: true
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: ./
      containerPath: /files

            